### ISSUE TITLE
panic on 32-bit arm

### ISSUE THREAD

**Issue by qsun** [maruel/circular#1]
The following sample code works fine in x86-64, but it will panic in 32-bit arm.

```
package main

import (
	"log"
	"os"

	"github.com/maruel/circular"
)

func main() {
	logBuffer := circular.New(10 * 1024 * 1024)
	defer func() {
		// Flush ensures all readers have caught up.
		logBuffer.Flush()
		// Close gracefully closes the readers.
		logBuffer.Close()
	}()

	log.SetOutput(logBuffer)
	go logBuffer.WriteTo(os.Stderr)

	log.Println("OK")
}
```

Compiling: `GOOS=linux GOARCH=arm GOARM=5 go build -ldflags "-s -w"`

file info: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped

panic:
```
./tmp
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1209c]

goroutine 1 [running]:
runtime/internal/atomic.goLoad64(0x244417c, 0x0, 0x7fffffff)
        /home/qsun/go-1.12.6/src/runtime/internal/atomic/atomic_arm.go:127 +0x1c
github.com/maruel/circular.(*writePosition).get(...)
        /home/qsun/go-path/src/github.com/maruel/circular/circular.go:302
github.com/maruel/circular.(*buffer).Flush(0x2444150)
        /home/qsun/go-path/src/github.com/maruel/circular/circular.go:163 +0x10c
main.main.func1(0xebfb8, 0x2444150)
        /tmp/test.go:14 +0x24
panic(0xc3110, 0x16c0d0)
        /home/qsun/go-1.12.6/src/runtime/panic.go:522 +0x1a0
runtime/internal/atomic.goLoad64(0x244417c, 0xdacac, 0x24441a4)
        /home/qsun/go-1.12.6/src/runtime/internal/atomic/atomic_arm.go:127 +0x1c
github.com/maruel/circular.(*writePosition).get(...)
        /home/qsun/go-path/src/github.com/maruel/circular/circular.go:302
github.com/maruel/circular.(*buffer).Write(0x2444150, 0x3220020, 0x17, 0x20, 0x0, 0x0, 0x0)
        /home/qsun/go-path/src/github.com/maruel/circular/circular.go:103 +0x80
log.(*Logger).Output(0x244c000, 0x2, 0x24120b8, 0x3, 0x0, 0x0)
        /home/qsun/go-1.12.6/src/log/log.go:172 +0x180
log.Println(0x242077c, 0x1, 0x1)
        /home/qsun/go-1.12.6/src/log/log.go:308 +0x54
main.main()
        /tmp/test.go:22 +0x1dc
#
```

**Comment by qsun** [comment]
CPU info on target:

```
# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 8.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : Freescale i.MX6 UltraLite (Device Tree)
Revision        : 0000
Serial          : 0000000000000000
```

Compiling environment
```
Linux qsun-ubuntu-gui 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
go version go1.12.6 linux/amd64
```

**Comment by maruel** [comment]
Thanks for the report. Sadly, I'm pretty sure this project has a real race corruption in it but didn't have the time to fix it. I'd appreciate a fix but I understand it may be time consuming to find the bug.
